DROP TABLE IF EXISTS url_checks;

DROP TABLE IF EXISTS urls;

CREATE TABLE urls (
  id                            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name                          VARCHAR(255) UNIQUE,
  created_at                    TIMESTAMP NOT NULL,
  CONSTRAINT pk_url1 PRIMARY KEY (id)
);

CREATE TABLE url_checks (
    id                            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    status_code                    INT,
    title                         VARCHAR(255),
    h1                            VARCHAR(255),
    description                   TEXT,
    url_id                         BIGINT REFERENCES urls(id),
    created_at                     TIMESTAMP NOT NULL,
    CONSTRAINT pk_url2 PRIMARY KEY (id)
);